[gcloud]
disabled = true

[python]
pyenv_version_name = true
pyenv_prefix = ""
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[cmd_duration]
disabled = true

[git_branch]
truncation_length = 12

